STAT_DEM_ADOUR=read.csv("/run/media/pageot/ADATA HD650/THESE/CLASSIFICATION/TRAITEMENT/SRTM/STAT_STRM_DT2017/STAT_DTADOUR_2017.csv",sep=",",dec=".",stringsAsFactors = FALSE)
STAT_DEM_ADOUR=na.omit(STAT_DEM_ADOUR)
hist(STAT_DEM_ADOUR$X_DEMmean)



STAT_DEM_TARN=read.csv("/run/media/pageot/ADATA HD650/THESE/CLASSIFICATION/TRAITEMENT/SRTM/STAT_STRM_DT2017/STAT_DTTARN_2017.csv",sep=",",dec=".",stringsAsFactors = FALSE)
STAT_DEM_TARN=na.omit(STAT_DEM_TARN)
hist(STAT_DEM_TARN$X_DEMmean)
