#!/usr/bin/env python3
# -*- coding: utf-8 -*-

df=pd.read_csv("/work/CESBIO/projects/Irrigation/dataExogene/T31TCJ/list_features_optic.txt",sep=',', header=None)
df1=df.T
df1.columns=["band_name"]
df1.index = np.arange(1, len(df1)+1)
df1["band"] = df1.index
df1["indice"] = df1.band_name.apply(lambda s: s[12:15])

list_channel=[]
f=df1.iloc[80:330]["band"].tolist()
for i in f:
    a = "channel "+ str(i)
    list_channel.append(a)
    
os.system("otbcli_ExtractROI -in /work/CESBIO/projects/Irrigation/dataExogene/T31TCJ/Sentinel2_T31TCJ_Features.tif -cl list_channel -out /work/CESBIO/projects/Irrigation/dataExogene/T31TCJ/testExtarct.tif")
